from crewai import Task

from agents.legal_drafter_agent import legal_drafter_agent
from tasks.case_intake_task import case_intake_task
from tasks.ipc_section_task import ipc_section_task
from tasks.legal_precedent_task import legal_precedent_task
from tasks.legal_reasoning_task import legal_reasoning_task
from tasks.explainability_task import explainability_task


legal_drafter_task = Task(
    agent=legal_drafter_agent,

    description=(
        "Using all the information generated by previous agents, produce a detailed "
        "legal case analysis report.\n\n"

        "The report must be structured into the following sections:\n\n"

        "1. Case Overview\n"
        "- Explain the issue in simple language\n"
        "- Summarize the events and parties involved\n\n"

        "2. Key Legal Issues\n"
        "- Identify the core legal questions involved in the case\n\n"

        "3. Relevant IPC Sections\n"
        "- List the IPC sections identified\n"
        "- Explain why they apply to the case\n\n"

        "4. Relevant Legal Precedents\n"
        "- Summarize the precedent cases\n"
        "- Explain how they relate to the issue\n\n"

        "5. Opponent Perspective\n"
        "- Summarize the prosecution/complainant argument\n\n"

        "6. Defence Perspective\n"
        "- Summarize the defense arguments\n\n"

        "7. Judicial Analysis\n"
        "- Provide balanced reasoning evaluating both sides\n"
        "- Explain legal interpretation of the IPC sections\n\n"

        "8. Final Legal Understanding\n"
        "- Provide a clear explanation of the likely legal interpretation\n"
        "- Explain what legal consequences may arise\n\n"

        "9. Step-by-Step Reasoning Explanation\n"
        "- Briefly summarize how the AI system analyzed the case step-by-step\n\n"

        "Use clear section headings and structured formatting.\n"
        "Ensure explanations are understandable to non-lawyers."
    ),

    expected_output=(
        "A detailed structured legal analysis report with clear headings, "
        "explanations of the issue, applicable laws, precedent cases, arguments "
        "from both sides, judicial reasoning, and a final understandable legal interpretation."
    ),

    context=[
        case_intake_task,
        ipc_section_task,
        legal_precedent_task,
        legal_reasoning_task,
        explainability_task
    ]
)